version: '3.4'

services:
  webapi:
    image: klinkby/clamrest
    build:
      context: src/Klinkby.ClamREST
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HOST=clamav
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - clamav
  clamav:
    image: mkodockx/docker-clamav:alpine
   
  

