version: '3.4'

services:
  webapi:
    image: klinkby/clamrest
    build:
      context: src/Klinkby.ClamREST
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - HOST=clamav
    depends_on:
      - clamav
    restart: always
  clamav:
    image: mkodockx/docker-clamav:alpine
    restart: always
  