version: '3.4'

services:
  webapi:
    image: klinkby/clamrest
    read_only: true
    build:
      context: src/Klinkby.ClamREST
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - HOST=clamav
    depends_on:
      - clamav
    restart: always
    tmpfs:
      - /tmp
    healthcheck:
      test: ["CMD", "wget", "http://localhost:5000/health", "-q", "-O", "-"]
      timeout: 3s
      interval: 1m
      retries: 3
  clamav:
    image: mkodockx/docker-clamav:alpine
    read_only: true
    restart: always
    tmpfs:
      - /run/clamav:uid=100
      - /tmp
    volumes:
      - ./volumes/clamav:/var/lib/clamav
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "3310"]
      timeout: 3s
      interval: 10s
      retries: 3
      