version: '3.4'

services:
  webapi:
    image: klinkby/clamrest
    build:
      context: src/Klinkby.ClamREST
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - HOST=clamav
    depends_on:
      - clamav
    healthcheck:
      test: ["CMD", "wget", "http://localhost:5000/health", "-q", "-O", "-"]
      timeout: 3s
      interval: 10s
      retries: 1
  clamav:
    image: mkodockx/docker-clamav:alpine
  